name: Issue Pipeline

on:
  issue_comment:
    types: [created]

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check the Issue state
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          if [ "${{ github.event_name }}" == "issues" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.issue.state }}" == "closed" ]; then
            echo "Issue is closed. Checking comment for approval or denial..."
          else
            echo "Not a relevant event. Exiting..."
            exit 1
          fi
          
      - name: Check for approaval state
        run: |
          echo "${{ github.event_path }}"
          comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
          last_comment_body=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $comments_url | jq -r '.[-1].body')
          echo "Last Comment Body: $last_comment_body"          
        
          if [[ "$last_comment_body" == "approve" ]]; then
            echo "Pipeline approved. Running the pipeline..."
          elif [[ "$last_comment_body" == "deny" ]]; then
            echo "Pipeline denied. Failing the pipeline."
            exit 1
          else
            echo "Action not identified. Pipeline denied. Failing the pipeline."
            exit 1
          fi
          
      - name: Extract the issue body and details
        run: |
          issue_body=$(jq -r '.issue.body' "${{ github.event_path }}")
          version=$(echo "$issue_body" | awk '/### VERSION/{flag=1; next} /###/{flag=0} flag' | tr -d '\n')
          path=$(echo "$issue_body" | awk '/### PATH/{flag=1; next} /###/{flag=0} flag' | tr -d '\n')
          branch=$(echo "$issue_body" | awk '/### BRANCH/{flag=1; next} /###/{flag=0} flag' | tr -d '\n')
          echo "$version"
          echo "$path"
          echo "$branch"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 14
