name: manual-trigger

on:
  issues:
    types:
      - edited
permissions:
  issues: write
  contents: read
  pages: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Manual Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ secrets.GITHUB_TOKEN }}
        approvers: MirzaJunaid96
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        ISSUE_BODY: "Please approve or deny the deployment of version v1.3.5."
        
    - name: Check if issue is approved
      if: github.event.issue.pull_request && contains(github.event.comment.body, '/approve')
      run: |
          ISSUE_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                       -H "Accept: application/vnd.github.v3+json" \
                       ${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.body')
          echo "Approved Issue Body: $ISSUE_BODY"
       
    - name: Deploy to environment
      run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
