name: HelloWorldPipeline

on:
  issues: 
    inputs:
     environment:
        description: 'Environment to Deploy on'
        required: true
     types:
       - closed
       - environment

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello, World!
      run: echo "Hello, World!"
