name: Your Pipeline

on:
  issue_comment:
    types:
      - created
  push:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check if the comment is on a closed issue
      run: |
        if [ "${{ github.event_name }}" == "issue_comment" ] && [ "${{ github.event.action }}" == "created" ] && [ "${{ github.event.issue.state }}" == "closed" ]; then
          echo "Issue is closed. Checking comment for approval or denial..."
        else
          echo "Not a relevant event. Exiting..."
          exit 0
        fi

    - name: Check comment for approval or denial
      run: |
        comment_body=$(jq -r .comment.body "${{ github.event_path }}")
        
        if [[ "$comment_body" == *"approve"* ]]; then
          echo "Pipeline approved. Running the pipeline..."
          # Add your pipeline execution command here
        elif [[ "$comment_body" == *"deny"* ]]; then
          echo "Pipeline denied. Not running the pipeline."
          exit 0
        else
          echo "No action required for this comment."
          exit 0
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install
