name: issue and workflow

on:
  issues:
    types:
      - closed
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to Deploy on'
        required: true
        type: environment

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Deployment Issue
      run: |
        const github = require('@actions/github');
        const core = require('@actions/core');

        const environment = core.getInput('environment');
        const issueTitle = `Deployment to ${environment}`;
        const issueBody = `Please review and close this issue to trigger deployment to ${environment}.`;

        const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

        const newIssue = await octokit.issues.create({
          owner: 'MirzaJunaid96', // Replace with your GitHub username
          repo: 'pipeline-approval', // Replace with your repository name
          title: issueTitle,
          body: issueBody,
        });

        core.setOutput('issue_number', newIssue.data.number);

  deploy:
    needs: create_issue
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Hello, World!
      run: echo "Hello, World! Deploying to $ENVIRONMENT"
