name: pull request comment

on:
  issues:
    types: closed

jobs:
  job01:
    # if: contains(github.event.issue.html_url, '/pull/')  # Check if the comment is associated with a pull request
    runs-on: [ubuntu-latest]

    steps:
      - name: say hello
        if: contains(github.event.comment.body, '/support')   # Check if the comment contains the keyword
        run: |
          echo say hello

      - name: test
        if: contains(github.event.comment.body, '/test')  # Check if the comment contains the keyword
        run: |
          echo test
