name: pull request comment

# on:
#   issue_comment:                                     
#     types: [created, edited, deleted]

jobs:
   run_pipeline:
    if: contains(github.event.issue.html_url, '/pull/')  # Check if the comment is associated with a pull request
    runs-on: ubuntu-latest

    steps:
      - name: Check if the comment is on a closed issue
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          ls $(pwd)
          echo "$GITHUB_CONTEXT"
          comment_body=$(jq -r .comment.body "${{ github.event_path }}")
          echo $comment_body
          if [ "${{ github.event_name }}" == "issues" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.issue.state }}" == "closed" ]; then
            echo "Issue is closed. Checking comment for approval or denial..."
          else
            echo "Not a relevant event. Exiting..."
            exit 0
          fi
      - name: Check comment for approval or denial
        run: |
          comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
          last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
          echo "Last Comment Body: $last_comment_body"    
      - name: say hello
        if: contains(github.event.comment.body, '/support')   # Check if the comment contains the keyword
        run: |
          echo say hello
      - name: test
        if: contains(github.event.comment.body, '/test')  # Check if the comment contains the keyword
        run: |
          echo test
