name: test

on:
  issues:
    types:
      - closed    
     

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check if the comment is on a closed issue
        env:
          GITHUB_TOKEN: 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
          VARS_CONTEXT: ${{ toJson(vars) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          ls $(pwd)
          echo "$GITHUB_CONTEXT" | jq . 
          # comment_body=$(jq -r .comment.body "${{ github.event_path }}")
          comment_body=$(jq -r ".event.issue.comments" "${{ github.event_path }}")
          echo $comment_body
          if [ "${{ github.event_name }}" == "issues" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.issue.state }}" == "closed" ]; then
            echo "Issue is closed. Checking comment for approval or denial..."
          else
            echo "Not a relevant event. Exiting..."
            exit 1
          fi

      - name: Check comment for approval or denial
        run: |
          echo "$GITHUB_CONTEXT" | jq . 
          comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
          echo "Comments URL: $comments_url"
          # last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
          comments=$(curl -s "${comments_url}" | jq '.')
          echo "Comments: $comments"
          last_comment_body=$(echo "$GITHUB_CONTEXT" | jq -r '.event.issue.comments_url | last(.[]).body')
          echo "Last Comment Body: $last_comment_body"          
        
          if [[ "$last_comment_body" == "approve" ]]; then
            echo "Pipeline approved. Running the pipeline..."
          elif [[ "$last_comment_body" == "deny" ]]; then
            echo "Pipeline denied. Failing the pipeline."
            exit 1
          else
            echo "Action not identified. Pipeline denied. Failing the pipeline."
            exit 1
          fi
      # - name: Run Pipeline
      #   if: success()  # Only run if the comment was processed successfully
      #   run: |
      #     # Your pipeline steps go here

      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 14
