name: test Pipeline

on:
  issues:
    types:
      - closed

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the comment is on a closed issue
        env:
          VARS_CONTEXT: ${{ toJson(vars) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          ls $(pwd)
          echo "$GITHUB_CONTEXT"
          comment_body=$(jq -r .comment.body "${{ github.event_path }}")
          echo $comment_body
          if [ "${{ github.event_name }}" == "issues" ] && [ "${{ github.event.action }}" == "closed" ] && [ "${{ github.event.issue.state }}" == "closed" ]; then
            echo "Issue is closed. Checking comment for approval or denial..."
          else
            echo "Not a relevant event. Exiting..."
            exit 0
          fi

      - name: Check comment for approval or denial
        id: check_approval
        run: |
          comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
          last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
          echo "Last Comment Body: $last_comment_body"

          if [[ "$last_comment_body" == *"approve"* ]]; then
            echo "Pipeline approved. Setting approval status to true..."
            echo "::set-output name=approval::true"
          elif [[ "$last_comment_body" == *"deny"* ]]; then
            echo "Pipeline denied. Setting approval status to false."
            echo "::set-output name=approval::false"
          else
            echo "No action required for this comment. Setting approval status to false."
            echo "::set-output name=approval::false"
          fi

      # - name: Run Pipeline
      #   if: success() && steps.check_approval.outputs.approval == 'true' # Only run if the comment was processed successfully and approval was received
      #   run: |
      #     # Your pipeline steps go here
      #     ./run_pipeline.sh

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
