name: ApproveOps

# on:
#   issue_comment:
#     types: [created]

jobs:
  approveops:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/approved')

    outputs: 
      approved: ${{ steps.check-approval.outputs.approved }}

    steps:
      # - name: Get GitHub App Installation Token
      #   id: get_installation_token
      #   uses: tibdex/github-app-token@v1
      #   with:
      #     app_id: 170284
      #     private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: ApproveOps - Check Approval
        id: check-approval
        uses: joshjohanning/approveops@v2
        with:
          approve-command: '/approved'
          # token: ${{ steps.get_installation_token.outputs.token }}
          # team-name: ${{ env.approver_team_name }}
          fail-if-approval-not-found: true
          post-successful-approval-comment: true
          successful-approval-comment: ':tada:  You were able to run the workflow because someone left an approval in the comments!! :tada:'

  migration:
    runs-on: ubuntu-latest
    needs: approveops
    if: ${{ needs.approveops.outputs.approved == 'true' }}

    steps:
      - name: Run Migration
        run: echo "run migration!"
