name: CallerWorkFlow

on:
  issues:
    types:
      - closed    
    inputs: 
      calledworkflow_name:
        description: 'Called workflow Name for Triggering'
        required: true
        default: 'test'
      
      CalledWorkflow_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'MirzaJunaid96'
      
      CalledWorkflow_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'approval'
